### ISSUE TITLE
Clone link not found

### ISSUE THREAD

**Issue by ouya99** [iotaledger/fpc-sim#2]
git clone https://github.com/iotaledger/res-sim-fpc.git as in README.me is not found

try just clone and it works

**Comment by gjeee** [comment]
git clone https://github.com/iotaledger/fpc-sim does work for me

**Comment by ouya99** [comment]
> Step 1. Build and run the simulation
> Clone the repository
> 
> git clone https://github.com/iotaledger/res-sim-fpc.git

@gjeee read my first comment. this link does not work

**Comment by gjeee** [comment]
but `git clone https://github.com/iotaledger/fpc-sim` DOES work

**Comment by ouya99** [comment]
@gjeee  read my 1st comment ;)

**Comment by gjeee** [comment]
ok you just want the typo to be fixed :-) i was just suggesting a link which does work

**Comment by ouya99** [comment]
I am not 100% sure its a typo. Seems to be referencing another version/project.

Just press clone button and you are fine, but if you follow the instructions you are stuck

**Comment by capossele** [comment]
It was a typo, now fixed, thanks. I'll close this issue.
